# Generated by Django 5.2.1 on 2025-05-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('choices', models.JSONField(help_text="A list of answer options, e.g., ['A', 'B', 'C', 'D']")),
                ('correct_answer', models.CharField(help_text='Must match one of the choices', max_length=255)),
            ],
        ),
    ]
